1 翻译 3 校对 完成
udacity-china-translation/srt-translation-2017-07-githubxiaowei pull request #1
Opened 2017-08-12 16:02 UTC by githubxiaowei

add 
oCCMSsCc4Iw.srt 

check
 JBiT_Nl-QtQ.srt 
q4yGy7F50zs.srt 
EwV5Vs2m33w.srt"

2017-08-13 03:12 UTC, githubxiaowei commented
@ivylee0919

2017-08-15 12:55 UTC, ivylee0919 requested changes
第一次提交，完成的很棒！👍
具体需要修改的内容都在各自的位置标出，再试一次 💪

2017-08-15 12:55 UTC, ivylee0919 commented on locales/zh-cn/JBiT_Nl-QtQ.srt
> +以及能否理解下面的巴科斯范式语法
👍相信你有查询资料，这里按照维基百科的翻译，很棒！“巴科斯范式”和“终结符”

2017-08-15 12:55 UTC, ivylee0919 commented on locales/zh-cn/JBiT_Nl-QtQ.srt
> +以非终结符 Sentence 为起始符的语法生成？
which of these sentences can be produced from the grammar here, starting from the non-terminal sentence?
下列句子中 哪些可以由以非终结符 Sentence 为起始符的语法生成？
这样会不会好一点？或者有没有什么更好的意见？
下列句子中 哪些可以由这个以非终结符 Sentence 开头的语法生成？

2017-08-15 12:55 UTC, ivylee0919 commented on locales/zh-cn/q4yGy7F50zs.srt
> +﻿1
放到视频中播放的话，编号 6 的后半句似乎应该放到编号 7 里面

2017-08-15 12:55 UTC, ivylee0919 commented on locales/zh-cn/EwV5Vs2m33w.srt
> +无法确认你是否提供了用户需要的所有产品
与上一句连起来读的话：你通过 A/B 测试无法确认你是否提供了用户需要的所有产品
似乎不是很通顺，后面的”你“去掉怎么样？
- 你通过 A/B 测试
- 无法确认是否提供了用户需要的所有产品

2017-08-15 12:55 UTC, ivylee0919 commented on locales/zh-cn/EwV5Vs2m33w.srt
> +你仍然无法知道是否缺少（用户需要的）其他产品
[中文字幕规范](https://github.com/udacity-china-translation/srt-translation-training-material/blob/master/tools/%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83.md)中关于括号的说明如下：
括号【( )】
- 添加说明时使用
- 使用英文括号，左括号左边、右括号右边各加一空格，与正文隔开 【例外：数学算式如 f(x) 不需要加空格】

2017-08-16 12:44 UTC, githubxiaowei commented on locales/zh-cn/JBiT_Nl-QtQ.srt
> +以非终结符 Sentence 为起始符的语法生成？
我觉得这里sentence作为起始符号（start symbol），翻译成开头有点不标准？
[https://zh.wikipedia.org/wiki/%E7%B5%82%E7%B5%90%E7%AC%A6%E8%88%87%E9%9D%9E%E7%B5%82%E7%B5%90%E7%AC%A6]
[https://en.wikipedia.org/wiki/Terminal_and_nonterminal_symbols]
”非终结符是可以被取代的符号。一个形式文法中必须有一个起始符号；这个起始符号属于非终结符的集合。”

2017-08-16 13:32 UTC, githubxiaowei commented
@ivylee0919  按要求修改好啦~

2017-08-16 13:58 UTC, ivylee0919 approved these changes
恭喜试译通过 💐

2017-08-16 13:58 UTC, merged